# Generated by Django 3.0.3 on 2021-02-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HazardEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(default='Unspecified', max_length=1024)),
                ('arabic', models.CharField(default='Unspecified', max_length=1024)),
            ],
        ),
    ]
