# Generated by Django 3.0.3 on 2021-02-24 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(default='Unspecified Control', max_length=1024)),
                ('arabic', models.CharField(default='Unspecified Control', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(default='Unspecified Haz', max_length=1024)),
                ('arabic', models.CharField(default='Unspecified Haz', max_length=1024)),
                ('icon', models.ImageField(default='default.png', upload_to='harzard_icons')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(default='Unspecified Location', max_length=1024)),
                ('arabic', models.CharField(default='Unspecified Location', max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='PPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(default='Unspecified PPE', max_length=1024)),
                ('arabic', models.CharField(default='Unspecified PPE', max_length=1024)),
                ('icon', models.ImageField(default='default.png', upload_to='ppe_icons')),
            ],
        ),
        migrations.AlterField(
            model_name='hazardeffect',
            name='arabic',
            field=models.CharField(default='Unspecified HazEf', max_length=1024),
        ),
        migrations.AlterField(
            model_name='hazardeffect',
            name='english',
            field=models.CharField(default='Unspecified HazEf', max_length=1024),
        ),
        migrations.CreateModel(
            name='TargetOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(default='Unspecified Tar/OP', max_length=1024)),
                ('arabic', models.CharField(default='Unspecified Tar/OP ', max_length=1024)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Location')),
            ],
        ),
    ]
