# Generated by Django 3.0.3 on 2021-02-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210224_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='arabic',
            field=models.CharField(default='عذرا ، المصطلح الحالي لم يترجم بعد.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='hazard',
            name='arabic',
            field=models.CharField(default='عذرا ، المصطلح الحالي لم يترجم بعد.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='hazardeffect',
            name='arabic',
            field=models.CharField(default='عذرا ، المصطلح الحالي لم يترجم بعد.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='location',
            name='arabic',
            field=models.CharField(default='عذرا ، المصطلح الحالي لم يترجم بعد.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='ppe',
            name='arabic',
            field=models.CharField(default='عذرا ، المصطلح الحالي لم يترجم بعد.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='targetoperation',
            name='arabic',
            field=models.CharField(default='عذرا ، المصطلح الحالي لم يترجم بعد.', max_length=1024),
        ),
    ]
