# Generated by Django 3.0.3 on 2021-02-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210224_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempPrint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.BooleanField(default=True)),
                ('swp', models.CharField(default='Unspecified', max_length=2000)),
                ('rev', models.CharField(default='Unspecified', max_length=2000)),
                ('loc', models.CharField(default='Unspecified', max_length=2000)),
                ('owner', models.CharField(default='Unspecified', max_length=2000)),
                ('date', models.CharField(default='Unspecified', max_length=2000)),
                ('hazards', models.CharField(default='Unspecified', max_length=5000)),
                ('ppes', models.CharField(default='Unspecified', max_length=5000)),
                ('hazeffs', models.CharField(default='Unspecified', max_length=5000)),
                ('controls', models.CharField(default='Unspecified', max_length=5000)),
            ],
        ),
    ]
